In [16]:
import pandas as pd
import numpy as np
df1 = pd.read_csv('/Users/ibb4n/Downloads/FireWeatherTest/California_Fire_Incidents_Modified_Again.csv')
df1

AcresBurned   Latitude   Longitude               Started  \
0          257314  37.857000 -120.086000  2013-08-17T15:25:00Z   
1           30274  34.585595 -118.423176  2013-05-30T15:28:00Z   
2           27531  33.709500 -116.728850  2013-07-15T13:43:00Z   
3           27440  39.120000 -120.650000  2013-08-10T16:30:00Z   
4           24251   0.000000    0.000000  2013-05-02T07:01:00Z   
...           ...        ...         ...                   ...   
1628           10  39.423833 -121.579738  2019-07-23T14:41:00Z   
1629           10  41.946220 -122.401570  2019-06-16T20:33:00Z   
1630           10  39.839580 -121.957000  2019-04-30T12:20:00Z   
1631            9  33.827979 -117.499619  2019-10-10T12:08:00Z   
1632            2  39.409722 -121.000556  2019-06-28T15:03:04Z   

                                  UniqueId  
0     5fb18d4d-213f-4d83-a179-daaf11939e78  
1     bf37805e-1cc2-4208-9972-753e47874c87  
2     a3149fec-4d48-427c-8b2c-59e8b79d59db  
3     8213f5c7-34fa-403b-a4bc-da2ace6e6625  
4     46731fb8-3350-4920-bdf7-910ac0eb715c  
...                                    ...  
1628  7955a367-99da-4047-9f69-cc60ad3208e6  
1629  fe63d965-9069-4a96-b9da-99d5fefdaa19  
1630  34abbc65-5bbe-474b-85c8-16d07bb5b503  
1631  6e93b252-99a3-4214-9921-238373b17535  
1632  b38c0563-b321-431b-9174-6336c5a0d449  

[1633 rows x 5 columns]

In [2]:
df2 = pd.read_csv('/Users/ibb4n/Downloads/FireWeatherTest/WeatherStationLocations.csv')
df2

Stn Id   Latitude   Longitude
0         2  36.336222 -120.112910
1         5  35.532556 -119.281790
2         6  38.535694 -121.776360
3         7  36.851222 -120.590920
4        12  39.608639 -121.824430
..      ...        ...         ...
145     260  41.798331 -122.463425
146     261  41.533989 -122.532279
147     262  38.065692 -121.071747
148     263  41.894592 -124.165043
149     264  39.777452 -120.273609

[150 rows x 3 columns]

In [3]:
dataset1 = df1.values
dataset1
#loc_dataset1 = dataset1[:,1:3]
#loc_dataset1

array([[257314, 37.857, -120.086, '2013-08-17T15:25:00Z',
        '5fb18d4d-213f-4d83-a179-daaf11939e78'],
       [30274, 34.585595, -118.423176, '2013-05-30T15:28:00Z',
        'bf37805e-1cc2-4208-9972-753e47874c87'],
       [27531, 33.7095, -116.72885, '2013-07-15T13:43:00Z',
        'a3149fec-4d48-427c-8b2c-59e8b79d59db'],
       ...,
       [10, 39.83958, -121.957, '2019-04-30T12:20:00Z',
        '34abbc65-5bbe-474b-85c8-16d07bb5b503'],
       [9, 33.827979, -117.499619, '2019-10-10T12:08:00Z',
        '6e93b252-99a3-4214-9921-238373b17535'],
       [2, 39.40972222, -121.0005556, '2019-06-28T15:03:04Z',
        'b38c0563-b321-431b-9174-6336c5a0d449']], dtype=object)

In [4]:
dataset2 = df2.values
dataset2

array([[   2.      ,   36.336222, -120.11291 ],
       [   5.      ,   35.532556, -119.28179 ],
       [   6.      ,   38.535694, -121.77636 ],
       [   7.      ,   36.851222, -120.59092 ],
       [  12.      ,   39.608639, -121.82443 ],
       [  13.      ,   38.753136, -120.7336  ],
       [  15.      ,   36.157972, -119.85143 ],
       [  35.      ,   37.358514, -118.40553 ],
       [  39.      ,   36.597444, -119.50404 ],
       [  41.      ,   33.042986, -115.41585 ],
       [  43.      ,   41.063767, -121.45602 ],
       [  44.      ,   33.964942, -117.33698 ],
       [  47.      ,   37.928258, -121.6599  ],
       [  52.      ,   35.305442, -120.66178 ],
       [  54.      ,   35.649861, -119.9593  ],
       [  56.      ,   37.096694, -120.7539  ],
       [  62.      ,   33.48665 , -117.22827 ],
       [  64.      ,   34.583144, -120.07924 ],
       [  68.      ,   32.759575, -115.73207 ],
       [  70.      ,   37.834822, -121.22319 ],
       [  71.      ,   37.645222, -121.1

In [5]:
empty_array = np.empty([1633,2])
dataset1 = np.append(dataset1,empty_array, axis=1)
dataset1

array([[257314, 37.857, -120.086, ...,
        '5fb18d4d-213f-4d83-a179-daaf11939e78', 0.0, 1.063e-320],
       [30274, 34.585595, -118.423176, ...,
        'bf37805e-1cc2-4208-9972-753e47874c87', 0.0, 5.14e-322],
       [27531, 33.7095, -116.72885, ...,
        'a3149fec-4d48-427c-8b2c-59e8b79d59db', 3.725474555587434e+174,
        1.159984119989337e-28],
       ...,
       [10, 39.83958, -121.957, ...,
        '34abbc65-5bbe-474b-85c8-16d07bb5b503', 5.4e-323, 5.4e-323],
       [9, 33.827979, -117.499619, ...,
        '6e93b252-99a3-4214-9921-238373b17535', 5e-323, 5e-323],
       [2, 39.40972222, -121.0005556, ...,
        'b38c0563-b321-431b-9174-6336c5a0d449', 5e-323, 5e-323]],
      dtype=object)

In [6]:
import math
closest_distance = 1000
closest_station = 0
for i in range(1633):
    for x in range(150):
        distance = math.sqrt(((dataset2[x,1]-dataset1[i,1]) ** 2)+((dataset2[x,2]-dataset1[i,2]) ** 2))
        if distance < closest_distance:
            closest_distance = distance
            closest_station = dataset2[x,0]
    closest_distance = closest_distance*69
    dataset1[i,5] = closest_distance
    dataset1[i,6] = closest_station
    closest_distance = 1000

In [7]:
dataset1

array([[257314, 37.857, -120.086, ...,
        '5fb18d4d-213f-4d83-a179-daaf11939e78', 42.81996545868889, 148.0],
       [30274, 34.585595, -118.423176, ...,
        'bf37805e-1cc2-4208-9972-753e47874c87', 12.772938493889585,
        204.0],
       [27531, 33.7095, -116.72885, ...,
        'a3149fec-4d48-427c-8b2c-59e8b79d59db', 15.915145255336949,
        239.0],
       ...,
       [10, 39.83958, -121.957, ...,
        '34abbc65-5bbe-474b-85c8-16d07bb5b503', 18.37377501668962, 12.0],
       [9, 33.827979, -117.499619, ...,
        '6e93b252-99a3-4214-9921-238373b17535', 14.671273799915596, 44.0],
       [2, 39.40972222, -121.0005556, ...,
        'b38c0563-b321-431b-9174-6336c5a0d449', 24.297087301406656, 84.0]],
      dtype=object)

In [8]:
#distance_counter = 0
for i in reversed(range(1633)):
    if dataset1[i,5] > 10:
        dataset1 = np.delete(dataset1,i,0)
print(dataset1.shape)

(410, 7)


In [9]:
dataset1

array([[3166, 34.288877, -116.941311, ...,
        'a1b14be5-a8cf-4e40-8588-96becf4c5879', 6.3101761774420755,
        199.0],
       [1984, 34.55048, -119.82429, ...,
        'abc61995-8bea-4be1-aa49-ee378ab3baaa', 9.841663053217754, 107.0],
       [712, 34.49149, -118.610044, ...,
        '39af7eac-c188-411f-8c8a-d165c5fca4a9', 7.803829211231, 204.0],
       ...,
       [12, 39.32889, -121.23431, ...,
        '42e2b6f0-2d63-4fbf-bbb4-4fc2eda4805d', 7.6976190454584525, 84.0],
       [11, 34.033117, -117.21545, ...,
        '6ad5dc4a-bd52-4cb4-9664-2ab606289d21', 5.819861896396764, 251.0],
       [10, 32.762706, -117.097441, ...,
        '2a516d14-36ce-43b0-b34c-7483759a9c84', 3.6855241384621094,
        184.0]], dtype=object)

In [14]:
import numpy
data = numpy.asarray(dataset1)
numpy.savetxt('nearestFireStation.csv', data, fmt='%s')